version: "3.8"

services:
  postgres_db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${MASTER_DB_USER}
      - POSTGRES_PASSWORD=${MASTER_DB_PASSWORD}
      - POSTGRES_DB=${MASTER_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - dev_shield_db:/var/lib/postgresql/data/
    restart: always
    healthcheck:
      test:
        ["CMD-SHELL", "pg_isready -U ${MASTER_DB_USER} -d ${MASTER_DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  server:
    container_name: dev_go_server
    build:
      context: .
      target: dev
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - ${DEBUGGER_PORT}:${DEBUGGER_PORT}
    depends_on:
      postgres_db:
        condition: service_healthy
    volumes:
      - .:/app:rw,delegated
      - ~/.aws/:/root/.aws:ro
    restart: always

volumes:
  dev_shield_db:
  pgadmin_data:
