# Staging Environment Configuration
# Pre-production testing environment

server:
  port: 8081
  environment: staging
  debug: false
  timezone: UTC

logger:
  level: info

database:
  host: shield-staging-db.amazonaws.com
  port: 5432
  user: shield_staging
  password: ${STAGING_DB_PASSWORD}
  name: shield_auth_staging
  sslMode: require
  maxIdleConns: 20
  maxOpenConns: 200
  connMaxLifetime: 2h

redis:
  host: shield-staging-redis.cache.amazonaws.com
  port: 6379
  password: ${STAGING_REDIS_PASSWORD}
  db: 0

cognito:
  userPoolId: ${STAGING_COGNITO_USER_POOL_ID}
  appClientId: ${STAGING_COGNITO_APP_CLIENT_ID}
  appClientSecret: ${STAGING_COGNITO_APP_CLIENT_SECRET}
  region: us-east-1
  domain: shield-staging.auth.us-east-1.amazoncognito.com

jwt:
  secret: ${STAGING_JWT_SECRET}
  expiry: 12h
  refreshExpiry: 72h

opa:
  serverUrl: http://shield-staging-opa:8181
  policyPath: /v1/data

observability:
  jaegerEndpoint: ${STAGING_JAEGER_ENDPOINT}
  prometheusEndpoint: ${STAGING_PROMETHEUS_ENDPOINT}
  enableMetrics: true
  enableTracing: true

rateLimiting:
  enabled: true
  requestsPerMinute: 500
  burst: 50

security:
  cors:
    allowedOrigins:
      - https://staging.shield.yourcompany.com
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowedHeaders:
      - Content-Type
      - Authorization
      - X-Requested-With
      - X-Device-Fingerprint
  trustedProxies: ${STAGING_TRUSTED_PROXIES}

features:
  multiFactorAuth: true
  deviceTracking: true
  sessionRotation: true

instrumentation:
  logging:
    withRequestBody: false
    withResponseBody: false
    withRequestHeader: true
    withResponseHeader: false
    withUserAgent: true
    withRequestId: true
    withSpanId: true
    withTraceId: true
    skipPaths:
      - /health
      - /metrics
      - /ping
    defaultLevel: info
    clientErrorLevel: warn
    serverErrorLevel: error
  openTelemetry:
    serviceName: shield-api-staging
    enableTracing: true
    enableMetrics: true
    withSpanId: true
    withTraceId: true
    withUserAgent: true
    withRequestBody: false
    withResponseBody: false
    withRequestHeader: false
    withResponseHeader: false
    filterPaths:
      - /health
      - /metrics
      - /ping
    filterMethods: []
