// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/onboarding/resendConfirmationCode": {
            "post": {
                "description": "Resend confirmation code",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Resend confirmation code",
                "parameters": [
                    {
                        "description": "resend confirmation code",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requestModels.ResendVerificationCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/onboarding/signup": {
            "post": {
                "description": "Supports Both Individual and Organization Account",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Sign up for a new account",
                "parameters": [
                    {
                        "description": "Add account",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requestModels.SignUp"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/v1/onboarding/verifyEmail": {
            "post": {
                "description": "Verify email",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Accounts"
                ],
                "summary": "Verify email",
                "parameters": [
                    {
                        "description": "verify email",
                        "name": "account",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requestModels.VerifyEmail"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.SSOType": {
            "type": "string",
            "enum": [
                "SAML",
                "OIDC"
            ],
            "x-enum-varnames": [
                "SAML",
                "OIDC"
            ]
        },
        "models.UserType": {
            "type": "string",
            "enum": [
                "INDIVIDUAL",
                "ORGANIZATION"
            ],
            "x-enum-varnames": [
                "Individual",
                "Org"
            ]
        },
        "requestModels.OrganizationInfo": {
            "type": "object",
            "required": [
                "emailDomain",
                "hasSSO",
                "name"
            ],
            "properties": {
                "emailDomain": {
                    "type": "string"
                },
                "hasSSO": {
                    "type": "boolean"
                },
                "name": {
                    "type": "string"
                },
                "ssoOptions": {
                    "$ref": "#/definitions/requestModels.SSOOptions"
                }
            }
        },
        "requestModels.ResendVerificationCode": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "requestModels.SSOOptions": {
            "type": "object",
            "required": [
                "clientId",
                "clientSecret",
                "redirectURL",
                "ssoType"
            ],
            "properties": {
                "clientId": {
                    "type": "string"
                },
                "clientSecret": {
                    "type": "string"
                },
                "redirectURL": {
                    "type": "string"
                },
                "ssoType": {
                    "$ref": "#/definitions/models.SSOType"
                }
            }
        },
        "requestModels.SignUp": {
            "type": "object",
            "required": [
                "email",
                "name",
                "password",
                "userType"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organizationInfo": {
                    "$ref": "#/definitions/requestModels.OrganizationInfo"
                },
                "password": {
                    "type": "string"
                },
                "userType": {
                    "$ref": "#/definitions/models.UserType"
                }
            }
        },
        "requestModels.VerifyEmail": {
            "type": "object",
            "required": [
                "confirmationCode",
                "email"
            ],
            "properties": {
                "confirmationCode": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
