definitions:
  models.SSOType:
    enum:
    - SAML
    - OIDC
    type: string
    x-enum-varnames:
    - SAML
    - OIDC
  models.UserType:
    enum:
    - INDIVIDUAL
    - ORGANIZATION
    type: string
    x-enum-varnames:
    - Individual
    - Org
  requestModels.OrganizationInfo:
    properties:
      emailDomain:
        type: string
      hasSSO:
        type: boolean
      name:
        type: string
      ssoOptions:
        $ref: '#/definitions/requestModels.SSOOptions'
    required:
    - emailDomain
    - hasSSO
    - name
    type: object
  requestModels.ResendVerificationCode:
    properties:
      email:
        type: string
    required:
    - email
    type: object
  requestModels.SSOOptions:
    properties:
      clientId:
        type: string
      clientSecret:
        type: string
      redirectURL:
        type: string
      ssoType:
        $ref: '#/definitions/models.SSOType'
    required:
    - clientId
    - clientSecret
    - redirectURL
    - ssoType
    type: object
  requestModels.SignUp:
    properties:
      email:
        type: string
      name:
        type: string
      organizationInfo:
        $ref: '#/definitions/requestModels.OrganizationInfo'
      password:
        type: string
      userType:
        $ref: '#/definitions/models.UserType'
    required:
    - email
    - name
    - password
    - userType
    type: object
  requestModels.VerifyEmail:
    properties:
      confirmationCode:
        type: string
      email:
        type: string
    required:
    - confirmationCode
    - email
    type: object
info:
  contact: {}
paths:
  /api/v1/onboarding/resendConfirmationCode:
    post:
      consumes:
      - application/json
      description: Resend confirmation code
      parameters:
      - description: resend confirmation code
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/requestModels.ResendVerificationCode'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Resend confirmation code
      tags:
      - Accounts
  /api/v1/onboarding/signup:
    post:
      consumes:
      - application/json
      description: Supports Both Individual and Organization Account
      parameters:
      - description: Add account
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/requestModels.SignUp'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Sign up for a new account
      tags:
      - Accounts
  /api/v1/onboarding/verifyEmail:
    post:
      consumes:
      - application/json
      description: Verify email
      parameters:
      - description: verify email
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/requestModels.VerifyEmail'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            type: string
      summary: Verify email
      tags:
      - Accounts
swagger: "2.0"
